# Generated by Django 4.1 on 2022-08-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='picture', upload_to='pics'),
            preserve_default=False,
        ),
    ]
